name: Python Tests with Debug

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ["3.8", "3.9", "3.10", "3.13"]

    - name: Install pytest
      run: pip install pytest selenium

    - name: Debug information
      run: |
        echo "=== Current directory structure ==="
        ls -la
        echo ""
        echo "=== Python files ==="
        find . -name "*.py" -type f
        echo ""
        echo "=== Test discovery ==="
        pytest --collect-only -v || echo "No tests found"

    - name: Run tests
      run: pytest -v
